import type { Metadata } from "next";
import { Inter_Tight, Sofia_Sans_Extra_Condensed } from "next/font/google";
import "./globals.css";
import Nav from "@/components/shared/Nav/Nav";
// import FinalCTA2 from "@/components/shared/FinalCTA2/FinalCTA2";
// import Footer from "@/components/shared/Footer/Footer";

const InterTight = Inter_Tight({
  variable: "--interTight",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900"],
});

const sofia = Sofia_Sans_Extra_Condensed({
  variable: "--sofia",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${InterTight.variable} ${sofia.variable}`}>
        <Nav />
        {children}
        {/* <FinalCTA2 /> */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
