import type { Metadata } from "next";
import {
  Inter,
  Inter_Tight,
  Sofia_Sans_Extra_Condensed,
} from "next/font/google";
import "./globals.css";
import Nav from "@/components/shared/Nav/Nav";
import { Toaster } from "react-hot-toast";

const InterTight = Inter_Tight({
  variable: "--interTight",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900"],
});

const inter = Inter({
  variable: "--inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900"],
});

const sofia = Sofia_Sans_Extra_Condensed({
  variable: "--sofia",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${InterTight.variable} ${sofia.variable} ${inter.variable}`}
      >
        <Toaster
          position='bottom-right'
          toastOptions={{
            className: "toastFont",
          }}
        />
        <Nav />
        {children}
      </body>
    </html>
  );
}
